on: push
name: 🚀 Deploy
jobs:
    web-deploy:
        name: 🚀 Deploy
        runs-on: ubuntu-latest
        steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v3

            - name: 📂 Sync files
              uses: SamKirkland/FTP-Deploy-Action@v4.3.4
              with:
                  server: www.it4pro-server3.be
                  username: hoeveloo
                  password: ${{ secrets.PROD_FTP_PWD }}
                  server-dir: domains/hoevelootens.be/public_html/
