on: push
name: 🚀 Deploy
jobs:
    bust-cache:
        name: 🔄 Bust cache
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Generate version string
              run: echo "VERSION=$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV

            - name: Add query string to JS references in HTML
              run: |
                  for file in $(find . -name "*.html"); do
                    echo "Processing $file"
                    sed -i "s|\(src=['\"]\)\(.*\.js\)\(['\"]\)|\1\2?v=${VERSION}\3|g" "$file"
                  done

            - name: Add query string to JS files importing other JS (optional)
              run: |
                  for file in $(find . -name "*.js"); do
                    echo "Processing $file"
                    sed -i "s|\(import .* from ['\"]\)\(.*\.js\)\(['\"]\)|\1\2?v=${VERSION}\3|g" "$file"
                  done
    web-deploy:
        name: 🚀 Deploy
        runs-on: ubuntu-latest
        steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v3

            - name: 📂 Sync files
              uses: SamKirkland/FTP-Deploy-Action@v4.3.4
              with:
                  server: www.it4pro-server3.be
                  username: hoeveloo
                  password: ${{ secrets.PROD_FTP_PWD }}
                  server-dir: domains/hoevelootens.be/public_html/
