on:
    push:
        branches:
            - master
name: Production Deployment
jobs:
    web-deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Get latest code
              uses: actions/checkout@v2

            - name: Sync files
              uses: SamKirkland/FTP-Deploy-Action@4.1.0
              with:
                  server: www.it4pro-server3.be
                  username: hoeveloo
                  password: ${{ secrets.PROD_FTP_PWD }}
